spring.datasource.url=jdbc:h2:mem:flotera;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
jwt.secret=KO/VVdfYjGhbFc5BGswC9HR8SeDtj18XFA7CABReH2+d7dDl6mc9Vjc7WYapF75D06M+jBRcswLjld3Ajxp6sA==
spring.mail.username = 3e2c9473fe103b
spring.mail.password = 5bf294718d1528